#!/bin/sh
echo "******************************************************"
echo "first migrate"
echo "******************************************************"
echo "docker-compose exec web python manage.py migrate"
docker-compose exec web python manage.py migrate
echo ""
echo ""
echo "******************************************************"
echo "copy static files"
echo "******************************************************"
echo "docker-compose run web python manage.py collectstatic --noinput"
docker-compose run web python manage.py collectstatic --noinput
echo ""
echo ""
echo "******************************************************"
echo "create user of django admin"
echo "******************************************************"
echo "docker-compose exec web python manage.py createsuperuser"
docker-compose exec web python manage.py createsuperuser
echo ""
echo ""
echo "******************************************************"
echo "create files of migration"
echo "******************************************************"
echo "docker-compose exec web python manage.py makemigrations"
docker-compose exec web python manage.py makemigrations
echo ""
echo ""
echo "******************************************************"
echo "second migrate"
echo "******************************************************"
echo "docker-compose exec web python manage.py migrate"
docker-compose exec web python manage.py migrate
echo ""
echo ""
echo "finish"
echo ""
echo ""