#!/bin/sh
echo "******************************************************"
echo "remove all containers and images and other data"
echo "******************************************************"
echo "docker system prune -a"
docker system prune -a
echo ""
echo ""
echo "******************************************************"
echo "stop docker service"
echo "******************************************************"
echo "sudo systemctl stop docker"
sudo systemctl stop docker
echo ""
echo ""
echo "******************************************************"
echo "remove files of docker settings"
echo "******************************************************"
echo "sudo rm -rf /var/lib/docker/"
sudo rm -rf /var/lib/docker/
echo ""
echo ""
echo "******************************************************"
echo "enable start up service"
echo "******************************************************"
echo "sudo systemctl enable docker"
sudo systemctl enable docker
echo ""
echo ""
echo "******************************************************"
echo "start docker services"
echo "******************************************************"
echo "sudo systemctl start docker"
sudo systemctl start docker
echo ""
echo ""
echo "finish"
echo ""
echo ""